[package]
name = "jobsched-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
jobsched-common = { path = "../crates/jobsched-common" }
serde_json = "1.0"

