[workspace]
resolver = "2"
members = ["crates/jobsched-common",
    "crates/runner",
    "crates/scheduler",
    "jobsched-cli", "jobschedd",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
